<a href="https://colab.research.google.com/github/PhoniciaAnne/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
pip install numpy

In [27]:
import numpy as np
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]],dtype = np.float128)
print(arr.shape)

arr = np.arange(2,8)
print(arr)

(2, 5)
[2 3 4 5 6 7]


In [28]:
d3_arr = np.zeros((2,3,4))
print(d3_arr)
print(d3_arr.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
24


In [29]:
arr_4d = np.ones((1,4,3,4))
print(arr_4d)
#x = blocks, y = 4 clolums , z = 3 rows , last = 4 numbers in each row
#item size
print(arr_4d.itemsize)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
8


In [30]:
array = np.full([2,3],5)
print(array)


[[5 5 5]
 [5 5 5]]


In [33]:
#Array Operations
sum =np.add([1,2],[1,2])
print("Sum is ",sum)
sub = np.subtract([7,8],[1,2])
print('subtraction is ',sub)
mul = np.multiply([1,2,3],[1,2,3])
print('multiplication is ',mul)
div = np.divide([10,20],[2,2])
print('divison is ',div)
mod = np.mod([10,15],[3,4])
print('modules is ',mod)
pow = np.power([2,3,4],[3,2,1])
print('power is ',pow)

Sum is  [2 4]
subtraction is  [6 6]
multiplication is  [1 4 9]
divison is  [ 5. 10.]
modules is  [1 3]
power is  [8 9 4]


In [38]:
#Relational operators
a = np.array([1,2,3])
b = np.array([2,2,1])

print("equals", a == b)
print('not equal', a!=b)
print('greater than', a>b)
print('less than', a<b)
print('<=', a<=b)



equals [False  True False]
not equal [ True False  True]
greater than [False False  True]
less than [ True False False]
<= [ True  True False]
2
[2 1]


In [41]:
#indexing
a = np.array([1,2,3,4,6,7])
print(a[1])
print(b[1:3])
print(a[1:4:2])
print(a[-3])

2
[2 1]
[2 4]
4


In [47]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)
print(arr[0:2,2:5])
print(arr[-2,-1])


[[1 2 3 4 5]
 [5 6 7 8 9]]
[[3 4 5]
 [7 8 9]]
5


In [49]:
#masking
a = np.array([1,4,2,3,4])
mask = a > 2
print(a[mask])

[4 3 4]


In [54]:
#Transpose of array
a = np.array(([1,2,3],[2,4,5]))
b = a.T
print(b)
print(a.shape)
print(b.shape)
print(a.swapaxes(0,1))

[[1 2]
 [2 4]
 [3 5]]
(2, 3)
(3, 2)
[[1 2]
 [2 4]
 [3 5]]


In [59]:
#random no genrations
a = np.random.randint(1,10,size =(5, 5))
print(a)
b = np.random.normal(size=3)
print(b)

[[9 2 3 7 9]
 [6 5 9 9 9]
 [7 3 7 3 3]
 [2 2 5 2 7]
 [3 4 9 2 7]]
[-0.95962882 -1.10298299 -0.38578358]


In [65]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [70]:
#aggregate functions
a = np.arange(1,10)
print("Minimum is ",np.min(a))
print("Maximum is ",np.max(a))
print("Mean is ",np.mean(a))
print("sum is ",np.sum(a))

Minimum is  1
Maximum is  9
Mean is  5.0
sum is  45


In [74]:
#basic arth functions
a = np.array([1,2,3,4,5])
print(np.add(a,2))
print(np.multiply(a,3))

[3 4 5 6 7]
[ 3  6  9 12 15]


In [77]:
#trigonometric
angles = np.array([0,np.pi/4,np.pi/3])
result = np.sin(angles)
print(result)
result = np.cos(angles)
print(result)

[0.         0.70710678 0.8660254 ]
[1.         0.70710678 0.5       ]


In [80]:
#exponential
a = np.array([2,3,4,5])
exp = np.exp(a)
print(exp)
#natural logartihmic fucntions
logfunction = np.log(a)
print(logfunction)

[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [84]:
a = np.array([2,3,4,5])
mean = a.mean()
print(mean)
print(a.std())

3.5
1.118033988749895


In [87]:
#comparison
a = np.array([1,5,2,7,9])
b = np.array([11,52,21,7,29])
print(np.greater(a,b))

[False False False False False]


In [88]:
#Brodcasting
a = np.array([1,5,2,7,9])
b = a + 2
print(b)

[ 3  7  4  9 11]


In [91]:
#ravel to flaten array
a = np.array(([1,2,3,4],[2,3,4,5]))
print(a.ravel())
print(a.flatten())

[1 2 3 4 2 3 4 5]
[1 2 3 4 2 3 4 5]




```
#diff btwn flatten and ravel
array will change in ravel if modyfied
array will not change even modified
```


In [99]:
a = np.array(([2,3],[1,2]))
b = a.ravel()
b[0] = 100
print(b)
c = a.flatten()
c[0] = 200
print(b)

[100   3   1   2]
[100   3   1   2]


In [105]:
#splititng
a = np.arange(15)
print(np.split(a,3))
#split unequals also -np.array_split(a,num)
b = np.arange(17)
print(np.array_split(b,4))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15, 16])]


In [108]:
#Adding
a = np.array(([1,2,3]))
b = np.array(([5,6,7]))
c = np.concatenate((a,b))
print(c)


[1 2 3 5 6 7]


In [111]:
#insert and removing elements
a = np.array(([1,2,3]))
print(np.append(a,[4,5]))
print(np.insert(a,2,[2,2]))
print(np.delete(a,2))

[1 2 3 4 5]
[1 2 2 2 3]
[1 2]


In [112]:
# row = axis = 0,col = 1
a = np.array(([2,3],[1,2]))
print(np.delete(a,1,axis= 0))

[[2 3]]
